### ISSUE TITLE
Problem with serverless-http and serverless-offline-scaleway

### ISSUE THREAD

**Issue by demangejeremy** [scaleway/serverless-offline-scaleway#26]
Hello team 👋 

I am currently using the serverless-http library to develop a serverless application using Scaleway's FaaS. Online, it works great. Only, locally (with serverless-offline-scaleway), I encounter some difficulties, here is a small example:

- file: app.js

```js
const serverless = require('serverless-http');
const express = require('express')
const app = express()

// Routes
app.get('/app', function (req, res) {
    res.send('Hello from app!')
})

app.get('/app/test', async function (req, res) {
    res.send('Hello from test!')
})

module.exports.handle = serverless(app);
```

- file: serverless.yml

```yaml
service: test

configValidationMode: off
useDotenv: true

provider:
  name: scaleway
  runtime: node14
  scwToken: ${env:SCW_SECRET}
  scwProject: ${env:SCW_ORG}

plugins:
  - serverless-scaleway-functions
  - serverless-offline-scaleway
  - serverless-dotenv-plugin

package:
  patterns:
    # - '!node_modules/**'
    - '!.gitignore'
    - '!.env.sample'
    - '!.git/**'

custom:
  serverless-offline-scaleway:
    noPrependStageInUrl: true
    httpPort: 5000

functions:
  app:
    handler: app.handle
    minScale: 1
```

With the query http://localhost:5000/app :

```
Hello from app!
```

But with http://localhost:5000/app/test :

```json
{"currentRoute":"get - /app/test","error":"Serverless-offline: route not found.","existingRoutes":["* - /app"],"statusCode":404}
```

Thank you in advance for your help. In the meantime, it is difficult to develop a whole application blindly, without a good local operation.
